### ISSUE TITLE
Скрипт управления группами

### ISSUE THREAD

**Issue by malashin** [TEHGAM/IA-red-attack#5]
### Задача:
Сделать новый скрипт для управления группами.

----

### Требования:
**Первоочередные:**
- [x] Графический интерфейс, чтобы всем было сразу видны все группы и кто в них находится.
- [x] Вызывается из меню действий по скролу мыши.
- [x] Возможность закрытия отряда.

**Второстепенные:**
- [x] Возможность кика из отряда командиром отряда.
- [x] Возможность передачи своих полномочий командира члену отряда. Командир становится простым членом группы. Доступно только командиру.
- [x] Возможность инвайта игроков в отряд командиром отряда. Инвайт работает и в закрытых, и открытых группах.
* ~~Возможность запроса на вступление в отряд. Командир должен его принять.~~

**Третьестепенные:**
* ~~Опция при которой все члены отряда могут принимать и инвайтить других игроков в группу.~~

---

### Комментарий:
За основу можно взять два уже существующих мода.

**Group manager от Aeroson:**
https://github.com/aeroson/a3-misc/blob/master/group_manager.sqf
Очень хороший функционал. Минус в том, что нет визуального интерфейса, работает через меню действий. При этом нужно подходить к людям для инвайта, кика. Написан очень понятно.

**DOM_squad от Xeno:**
https://github.com/TEHGAM/IA-red-attack/tree/master/co60_AW_Invade_Annex_2_79.Altis/scripts/DOM_squad
Есть визуальный интерфейс, он нам и нужен. Есть лок групп, но он перестал работать.

Другими словами функционал нужен из **Group Manager** (можно понять какие функции вызвать в Арме для достижения поставленных целей), а интерфейс с **Dom_squad**.

**Comment by ToxaBes** [comment]
Можно ли меня добавить сюда как collaborator чтобы я мог назначать баги на себя и коммитить в dev ветку? И надо придумать как мерджить в ADR (за синих) то что мы фиксим в Red Lynx (за красных) если баг общий (например этот баг).

**Comment by ToxaBes** [comment]
Пилю потихоньку DOM_Sqiad от Xeno. Закрытие отрядов починил, кик из отряда сделал, прикручиваю инвайты. В ходе работы продумал все варианты взаимодействия между игроками и появилась пара возражений по требованиям:

> Возможность передачи своих полномочий командира члену отряда. Командир становится простым членом группы. Доступно только командиру.

Как часто это было нужно? На моей памяти - ни разу. Также этот пункт дублирует следующую логику - новому командиру выйти из отряда, залочить новый отряд и прислать приглашения тем кому хочет. По выходу из старый группы, следующий по списку игрок становиться командиром группы.

> Возможность запроса на вступление в отряд. Командир должен его принять.

Я прям вижу как игрок настойчиво долбит по кнопке и спамит командира отряда приглашением. Нужно оставить командиру отряда возможность полного игнора надоедливого игрока (долбиться в отряд правилами не запрещено....). Логика следующая: игрок пишет/говорит в синий канал просьбу командиру. Командир отправляет инвайт. Если не хочет видеть игрока в группе, отвечает "нет", если начинается спам в голосовом чате - просто ставит игрока на Mute и спокойно продолжает играть.

> Опция при которой все члены отряда могут принимать и инвайтить других игроков в группу.

Вообще теряется смысл командира отряда. Хочешь пригласить своего друга в отряд - напиши/скажи в зеленый канал командиру своей группу просьбу отправить инвайт.

Все эти требования можно реализовать, но я думаю что мы не должны превращать управление отрядами в управление космическим кораблем и плодить дублирующийся функционал. Если я упустил вариант когда без этих пунктов реально не обойтись - напиши, обсудим.

**Comment by malashin** [comment]
> Возможность передачи своих полномочий командира члену отряда. Командир становится простым членом группы. Доступно только командиру.

На мой взгляд, очень нужная функция. Куда проще передать управление, чем создавать каждый раз новый отряд.

Допустим, командир уходит АФК, отдает лидера своему заместителю и говорит, чтобы тот управлял отрядом, пока его нет.
Допустим, командир занят командованием и не хочет больше заниматься инвайтами, отдает лидера заместителю.
```sqf
(group _this(0)) selectLeader _this(0);
```
---
> Возможность запроса на вступление в отряд. Командир должен его принять.

> Опция при которой все члены отряда могут принимать и инвайтить других игроков в группу.

Эти две функции не такие важные. Не делай их.

---

Есть еще вариант, что лидер будет спамить игроков инвайтами.

**Comment by malashin** [comment]
Сделал набросок интерфейса, может пригодится.

![Image](http://i.imgur.com/75kAqPW.png)

**Comment by ToxaBes** [comment]
> На мой взгляд, очень нужная функция. Куда проще передать управление, чем создавать каждый раз новый отряд.
Допустим, командир уходит АФК, отдает лидера своему заместителю и говорит, чтобы тот управлял отрядом, пока его нет.
Допустим, командир занят командованием и не хочет больше заниматься инвайтами, отдает лидера заместителю.

Ты прав, я забыл про эти ситуации. Сделаю эту фичу.

По интерфейсу, идея интересная, но есть пара замечаний:

1. На скрине 2 противоположных действия (кик/сделать командиром) находятся слишком близко друг к другу.  Легко промахнуться и кикнуть будущего командира )
2. Верхняя полоса с подсказкой по иконкам сбивает с толку. Первое желание - кликнуть по этим иконкам. Также полоса занимает много места и вместе с большой надписью крадет половину высоты ряда. Нам нужно чтобы максимальное количество рядов было видно без прокрутки.

Я сделал расположение кнопок kick/invite иначе. Если командир группы кликает по игроку из своей группы - между кнопками Lock и Leave появляется кнопка Kick (я использую stringable.xml так что скрины на русском). 

![1](https://cloud.githubusercontent.com/assets/3309152/10262994/6847bcd0-69ef-11e5-9520-ebf3f85b8834.png)

Если командир кликает по игроку из чужой группы, то в той группе между кнопками  Lock и Leave появляется кнопка Invite. 

![2](https://cloud.githubusercontent.com/assets/3309152/10262997/74a26958-69ef-11e5-8fa6-03124a98b921.png)
Мне кажется так проще и логичнее.

Чужой закрытый отряд выглядит вот так

![3](https://cloud.githubusercontent.com/assets/3309152/10263003/7ef304c6-69ef-11e5-9ce9-f4fed387e822.png)

Но из него по прежнему можно приглашать людей в свой отряд. 

![4](https://cloud.githubusercontent.com/assets/3309152/10263004/86d173c6-69ef-11e5-8dc8-49a1e899ffe6.png)

Из твоего варианта возьму цвета текста, большую надпись и возможно вариант передачи полномочий командира. После тестирования решим - пойдет или надо менять.

**Comment by malashin** [comment]
Если иконка будет использоваться только для одного действия, то смысла в этой иконке мало. Только в заблуждение будет вводить. Придётся текстом писать, как и остальные кнопки.

Тут либо широкие фреймы делать под 4 кнопки или конпки в два ряда раскидывать.

1.

Закрыть/Открыть | Пригласить/Выгнать | Повысить | Покинуть/Вступить
--- | --- | --- | ---

---

2.

Закрыть/Открыть | Покинуть/Вступить
--- | ---
Пригласить/Выгнать | Повысить

Второй вариант логично сделать так, чтобы у членов отряда его вообще не видно было, включая высоту фрейма. Если ты лидер, то ты видишь этот ряд.

---

3.

Есть еще вариант поставить **Повысить** в верхний ряд справа от названия группы. Но это не круто в плане дизайна интерфейса. :)

**Comment by malashin** [comment]
На счет оформления сильно не парься, цвета там, шрифты, иконки. Я могу потом это сам сделаю уже. Главное чтобы всё на своих местах было и функционал работал.

**Comment by ToxaBes** [comment]
Согласен, иконку не стоит использовать. Из иконок будет только "замок" для обозначения закрытого отряда. Кнопку "Повысить" сделал так: при одинарном клике на участнике группы появляется кнопка Выгнать. При двойном клике - вместо нее будет показана кнопка Повысить.
По цветам -  уже добавил цветов (необходимый минимум). После того как все будет готово - потестим и обсудим, главное оставить интерфейс простым и понятным. 

Также нашел пару багов, например при выходе/входе в группу на долю секунды показываются все 50 окон групп - получается мерцание которое раздражает (пофиксил). Еще были проблемы с вертикальным и горизонтальным скролами всей страницы (пофиксил).

Мне нужна твоя помощь в следующем: в каждой строке списка слева от имени игрока есть место, которое сейчас пустое. Там место для иконки. Подумай, что можно там показать, нужно ли это и и подготовь пути к иконкам. Можно например показывать какие-нибудь маленькие стандартные белые иконки класса игрока (медик, инженер и т.д.), так медик открыв меню сразу увидит в какой группе не хватает медика и т.д. Если смысла особого в этом нет, оставим как есть.

**Comment by malashin** [comment]
![Image](http://i.imgur.com/gAiyspd.png)

```sqf
<img image='\a3\ui_f\data\map\VehicleIcons\iconman_ca.paa' size='1.0' />
<img image='\a3\ui_f\data\map\VehicleIcons\iconmanat_ca.paa' size='1.0' />
<img image='\a3\ui_f\data\map\VehicleIcons\iconmanengineer_ca.paa' size='1.0' />
<img image='\a3\ui_f\data\map\VehicleIcons\iconmanexplosive_ca.paa' size='1.0' />
<img image='\a3\ui_f\data\map\VehicleIcons\iconmanleader_ca.paa' size='1.0' />
<img image='\a3\ui_f\data\map\VehicleIcons\iconmanmedic_ca.paa' size='1.0' />
<img image='\a3\ui_f\data\map\VehicleIcons\iconmanmg_ca.paa' size='1.0' />
<img image='\a3\ui_f\data\map\VehicleIcons\iconmanofficer_ca.paa' size='1.0' />
<img image='\a3\ui_f\data\map\VehicleIcons\iconmanrecon_ca.paa' size='1.0' />
<img image='\a3\ui_f\data\map\VehicleIcons\iconmanvirtual_ca.paa' size='1.0' />
```

Виртуал нам особо не нужен, но можно поставить раз уж делаем.
Рикон лучше не использовать и указать реальные классы. "Разведчик-санитар" - медик, "Разведчик" - обычный солдат и т.д. Это более важная информация и иконка почему-то очень похожая на иконку командира отделения.

---

Можно еще так путь к иконке получить:
```sqf
_v = typeOf player;
_d = getText(configFile >> "CfgVehicles" >> _v >> "icon");
_i = getText(configFile >> "CfgVehicleIcons" >> _d);
```
На выходе _i == \a3\ui_f\data\map\VehicleIcons\iconmanmedic_ca.paa, если ты медик. Разведчики нормально по классам распределены.

**Comment by ToxaBes** [comment]
То что нужно, огромное спасибо!

**Comment by ToxaBes** [comment]
Еще пара просьб:
1. Вырисовывается симпатичный интерфейс и на его фоне иконка "Замок" выглядит ужасно. Если есть другая стандартная иконка (не обязательно в виде замка), которая даст понять игроку что отряд закрыт, подскажи путь к ней.

2. Есть ли возможность текущую ширинуХвысоту экрана игрока? Если да то можно быстро рассчитывать влезают ли группы в один экран или нет и показывать/скрывать вертикальный скорлл справа. Сейчас у нас он показывается всегда, т.к. в диалоге 50 скрытых групп и место они занимают, хоть и не видны игроку.

**Comment by malashin** [comment]
1.
![Image](http://i.imgur.com/EJyqOC4.png)

---

2.
https://community.bistudio.com/wiki/getResolution

**Comment by ToxaBes** [comment]
Текущий статус:

1. Отказался от идеи прятать вертикальный скролбар (он не спроста был оставлен) - невозможно правильно отловить все варианты при нестандартных настройках, например когда у игрока включен режим "В окне" и стоит нестандартное resolution/aspect ratio. 
2. Делаю вторую часть процесса инвайта: после сообщения о приглашении игрок открывает меню отрядов и.... я пока придумал показывать кнопку "Вступить" даже если отряд закрыт и возможно выделить ее текст каким-то цветом (для незакрытых отрядов вообще ничего не меняется). 

Остальные возможности готовы.

**Comment by malashin** [comment]
2.
Либо вступить не видно вообще, пока инвайт не получит, либо блеклый серый цвет надписи сделать.

**Comment by ToxaBes** [comment]
Скрипт готов к тестированию, нужно минимум 3 человека (я с ботами проверил что смог, но закрытие группы и инвайт с ними толком не потестить).
Доступа к dev ветке у меня нет, если сделаю pull-request он сольется с предыдущим pull-request (спецоперации), прикрепить сюда pbo файл или архив github не дает. Форум тоже не дает делать прикреплять файлы. Давай email, отправлю тебе .pbo файл. Там пустая MP миссия на 10 голов с прикрученным скриптом управления группами, т.е. можно сразу запускать и тестить.

**Comment by malashin** [comment]
Кинул в личку на форуме.

**Comment by ToxaBes** [comment]
Отправил.

**Comment by ToxaBes** [comment]
Эту задачу можно закрывать.
